# CI pipeline for jira-terminal-client

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: pip install -r requirements.txt
  displayName: 'Install Python requirements'

- script: find . -name "*.py" -exec pylint --disable=R,C {} \;
  displayName: 'Linting python files'

